In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[ 'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]


In [4]:
# Define the vocab size
voc_size = 10000

In [5]:
# OHE representation for each word
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4584, 6664, 824, 1074],
 [4584, 6664, 824, 9955],
 [4584, 529, 824, 370],
 [8737, 672, 1028, 5642, 18],
 [8737, 672, 1028, 5642, 8491],
 [8009, 4584, 3149, 824, 6807],
 [910, 2898, 5989, 5642]]

In [16]:
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [18]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print (embedded_docs)

[[   0    0    0    0 4584 6664  824 1074]
 [   0    0    0    0 4584 6664  824 9955]
 [   0    0    0    0 4584  529  824  370]
 [   0    0    0 8737  672 1028 5642   18]
 [   0    0    0 8737  672 1028 5642 8491]
 [   0    0    0 8009 4584 3149  824 6807]
 [   0    0    0    0  910 2898 5989 5642]]


In [19]:
# Feature Representation 
dim = 10

In [20]:
model = Sequential()

model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))

model.compile(optimizer='adam', loss='mse')

In [21]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step


array([[[-0.01075865,  0.00188442, -0.02438608,  0.03926853,
         -0.04194225,  0.02895726,  0.04639509, -0.02207583,
         -0.00249289, -0.02507201],
        [-0.01075865,  0.00188442, -0.02438608,  0.03926853,
         -0.04194225,  0.02895726,  0.04639509, -0.02207583,
         -0.00249289, -0.02507201],
        [-0.01075865,  0.00188442, -0.02438608,  0.03926853,
         -0.04194225,  0.02895726,  0.04639509, -0.02207583,
         -0.00249289, -0.02507201],
        [-0.01075865,  0.00188442, -0.02438608,  0.03926853,
         -0.04194225,  0.02895726,  0.04639509, -0.02207583,
         -0.00249289, -0.02507201],
        [ 0.04666663,  0.03008002,  0.00591079,  0.02919469,
          0.04284241, -0.03789201,  0.03737209,  0.00228506,
         -0.01105837, -0.0303889 ],
        [ 0.03830994,  0.00177593, -0.02103581, -0.03565304,
          0.04965113, -0.03591656, -0.03975559, -0.02807912,
         -0.01179495, -0.03841319],
        [-0.01353987,  0.04980084, -0.00932877,  0.0